---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-app-oidc-client
  namespace: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "29"
type: Opaque
stringData:
  clientSecret: {{ .Values.rhbk.helloWorldApp.clientSecret | quote }}
  basicAuth: {{ printf "%s:%s" .Values.rhbk.helloWorldApp.clientId .Values.rhbk.helloWorldApp.clientSecret | b64enc | quote }}
