---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: {{ .Values.namespaces.exampleApps }}
  annotations:
    argocd.argoproj.io/sync-wave: "27"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app-container
        image: docker.io/testcontainers/helloworld
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-app
  namespace: {{ .Values.namespaces.exampleApps }}
  annotations:
    argocd.argoproj.io/sync-wave: "27"
spec:
  selector:
    app: hello-world-app
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-world-app
  namespace: {{ .Values.namespaces.exampleApps }}
  labels:
    app: hello-world-app
    deployment: hello-world-app
    service: hello-world-app
  annotations:
    argocd.argoproj.io/sync-wave: "28"
spec:
  parentRefs:
  - name: main-gateway
    namespace: istio-ingress
    sectionName: hello-world-app
  hostnames:
  - hello-world-app.{{ .Values.gwapiDomain }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: hello-world-app
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-world-app-callback
  namespace: {{ .Values.namespaces.exampleApps }}
  annotations:
    argocd.argoproj.io/sync-wave: "29"
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: main-gateway
    namespace: istio-ingress
  hostnames:
  - hello-world-app.{{ .Values.gwapiDomain }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /auth/callback
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: hello-world-app
  namespace: {{ .Values.namespaces.exampleApps }}
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: hello-world-app
  overrides:
    strategy: merge
    rules:
      authentication:
        oidc:
          credentials:
            cookie:
              name: jwt
          jwt:
            issuerUrl: {{ include "rhcl.oidc.issuerUrl" . | quote }}
            {{- if .Values.externalIAM.enabled }}
            jwksUrl: {{ include "rhcl.oidc.jwksUrl" . | quote }}
            {{- end }}
          priority: 0
      response:
        unauthenticated:
          code: 302
          headers:
            location:
              value: {{ include "rhcl.oidc.loginRedirectUrl" . | quote }}
            set-cookie:
              expression: |
                "target=" + request.path + "; domain=hello-world-app.{{ .Values.gwapiDomain }}; HttpOnly; SameSite=Lax; Path=/; Max-Age=3600"
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: hello-world-app-callback
  namespace: {{ .Values.namespaces.exampleApps }}
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: hello-world-app-callback
  overrides:
    strategy: merge
    rules:
      metadata:
        token:
          priority: 0
          when:
          - predicate: request.query.split("&").map(entry, entry.split("=")).filter(pair, pair[0] == "code").map(pair, pair[1]).size() > 0
          http:
            url: {{ include "rhcl.oidc.accessTokenUrl" . | quote }}
            method: POST
            contentType: application/x-www-form-urlencoded
            sharedSecretRef:
              name: hello-world-app-oidc-client
              key: basicAuth
            credentials:
              authorizationHeader:
                prefix: "Basic "
            body:
              expression: |
                "code=" + request.query.split("&").map(entry, entry.split("=")).filter(pair, pair[0] == "code").map(pair, pair[1])[0] + "&grant_type=authorization_code&redirect_uri=http%3A%2F%2Fhello-world-app.{{ .Values.gwapiDomain }}%2Fauth%2Fcallback&client_id={{ .Values.rhbk.helloWorldApp.clientId }}"
      authorization:
        location:
          priority: 1
          opa:
            allValues: true
            rego: |
              cookies := { name: value | raw_cookies := input.request.headers.cookie; cookie_parts := split(raw_cookies, ";"); part := cookie_parts[_]; kv := split(trim(part, " "), "="); count(kv) == 2; name := trim(kv[0], " "); value := trim(kv[1], " ")}
              location := concat("", ["http://hello-world-app.{{ .Values.gwapiDomain }}", cookies.target]) { input.auth.metadata.token.id_token; cookies.target }
              location := "http://hello-world-app.{{ .Values.gwapiDomain }}" { input.auth.metadata.token.id_token; not cookies.target }
              location := {{ include "rhcl.oidc.loginRedirectUrl" . | quote }} { not input.auth.metadata.token.id_token }
              allow = true
        deny:
          priority: 2
          opa:
            rego: allow = false
      response:
        unauthorized:
          code: 302
          headers:
            location:
              expression: auth.authorization.location.location
            set-cookie:
              expression: |
                "jwt=" + auth.metadata.token.id_token + "; domain=hello-world-app.{{ .Values.gwapiDomain }}; HttpOnly; SameSite=Lax; Path=/; Max-Age=3600"
---
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: hello-world-app
  namespace: {{ .Values.namespaces.exampleApps }}
  annotations:
    argocd.argoproj.io/sync-wave: "29"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  limits:
    my-limits:
      rates:
        - limit: 5
          window: 10s
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: hello-world-app
