---
apiVersion: v1
kind: Secret
metadata:
  name: red-app-oidc-client
  namespace: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "34"
type: Opaque
stringData:
  clientSecret: {{ .Values.rhbk.redApp.clientSecret | quote }}
  basicAuth: {{ printf "%s:%s" .Values.rhbk.redApp.clientId .Values.rhbk.redApp.clientSecret | b64enc | quote }}
