---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-app-keycloak-client
  namespace: {{ .Values.namespaces.rhbk }}
  annotations:
    argocd.argoproj.io/sync-wave: "24"
type: Opaque
stringData:
  clientSecret: {{ .Values.rhbk.helloWorldApp.clientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: red-app-keycloak-client
  namespace: {{ .Values.namespaces.rhbk }}
  annotations:
    argocd.argoproj.io/sync-wave: "24"
type: Opaque
stringData:
  clientSecret: {{ .Values.rhbk.redApp.clientSecret | quote }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: rhcl-realm
  namespace: {{ .Values.namespaces.rhbk }}
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  keycloakCRName: keycloak
  realm:
    realm: rhcl
    enabled: true
    displayName: "RHCL PoC"
    sslRequired: none
    clients:
      - clientId: hello-world-app
        name: "Hello World App"
        enabled: true
        protocol: openid-connect
        publicClient: true
        standardFlowEnabled: true
        directAccessGrantsEnabled: false
        fullScopeAllowed: true
        redirectUris:
          - "*"
        webOrigins:
          - "*"
      - clientId: {{ .Values.rhbk.redApp.clientId | quote }}
        name: "Red App"
        enabled: true
        protocol: openid-connect
        publicClient: false
        secret: {{ .Values.rhbk.redApp.clientSecret | quote }}
        standardFlowEnabled: false
        directAccessGrantsEnabled: false
        serviceAccountsEnabled: true
        fullScopeAllowed: true
    users:
      - username: demo
        enabled: true
        emailVerified: true
        email: demo@example.com
        firstName: Demo
        lastName: User
        credentials:
          - type: password
            value: demo123
            temporary: false
