{{- if .Values.htpasswd.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.htpasswd.secretName }}
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  htpasswd: "{{ .Values.htpasswd.username }}:{{ .Values.htpasswd.passwordHash }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.htpasswd.clusterAdminBindingName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: User
    name: {{ .Values.htpasswd.username }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
