---
apiVersion: v1
kind: Secret
metadata:
  name: red-app-consumer
  namespace: {{ .Values.namespaces.exampleApps }}
  annotations:
    argocd.argoproj.io/sync-wave: "34"
type: Opaque
stringData:
  clientId: {{ .Values.rhbk.redApp.clientId | quote }}
  clientSecret: {{ .Values.rhbk.redApp.clientSecret | quote }}
